Repository zeforgezenica/busez, pull requests merged in 2024-10, with the labels that each got.

#79 Setup shadcn
  frontend/components.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/globals.css
  frontend/src/app/lib/utils.ts
  frontend/tailwind.config.ts
Labels: hacktoberfest, hacktoberfest-accepted

#80 Monorepo setup with pnpm + turbo
  .gitignore
  CONTRIBUTING.md
  README.md
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  frontend/package.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: hacktoberfest

#91 Update search results
  backend/package-lock.json
  frontend/components.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/ui/button.tsx
  frontend/src/app/components/ui/card.tsx
  frontend/src/app/globals.css
  frontend/src/app/routes/RouteSearchResult.tsx
  frontend/tsconfig.json
Labels: hacktoberfest-accepted

#97 Refactor
  frontend/src/app/components/DateSelector.tsx
  frontend/src/app/components/Footer.tsx
  frontend/src/app/components/RouteDetailsModal.tsx
  frontend/src/app/components/StationSelect.tsx
  frontend/src/app/components/StationStep.tsx
  frontend/src/app/lib/timeUtils.ts
  frontend/src/app/lib/utils.ts
  frontend/src/app/routes/RouteProgressStepper.tsx
  frontend/src/app/routes/RouteSearch.tsx
  frontend/src/app/routes/RouteSearchResult.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#96 map selector component
  frontend/package-lock.json
  frontend/package.json
  frontend/public/departureSelect.png
  frontend/public/destinationSelect.png
  frontend/public/target.png
  frontend/src/app/components/MapSelector.tsx
  frontend/src/app/components/mapIcons.ts
  frontend/src/app/globals.css
  frontend/src/app/mapselector/MapComponent.tsx
  frontend/src/app/routes/RouteSearch.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#109 Convert station selection comboboxes to shadcn/ui
  frontend/package.json
  frontend/src/app/components/StationSelect.tsx
  frontend/src/app/components/ui/command.tsx
  frontend/src/app/components/ui/popover.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#112 Updated with new favicon
  Zebusez logo.png
  frontend/src/app/favicon.ico
Labels: hacktoberfest, hacktoberfest-accepted

#122 Add shadcn datepicker
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/DateSelector.tsx
  frontend/src/app/components/StationSelect.tsx
  frontend/src/app/components/ui/calendar.tsx
  frontend/src/app/routes/RouteSearch.tsx
  pnpm-lock.yaml
Labels: Type: Enhancement

#145 ci: add test steps
  .github/workflows/ci.yml
  .gitignore
  frontend/jest.config.ts
  frontend/package.json
  frontend/src/app/handlers/route.progress.test.ts
  pnpm-lock.yaml
  turbo.json
Labels: hacktoberfest, hacktoberfest-accepted
